### ISSUE TITLE
copmile error 

### ISSUE THREAD

**Issue by 40ft** [psaravan/FileBrowserView#1]
`$ ./gradlew build

:library:compileReleaseJava
FileBrowserView/library/src/main/java/com/psaravan/filebrowserview/lib/ListLayout/ListLayoutAdapter.java:112: error: cannot find symbol
                holder.fileFolderIcon.setImageResource(R.drawable.icon_folderblue);
                                                                 ^
  symbol:   variable icon_folderblue
  location: class drawable
FileBrowserView/library/src/main/java/com/psaravan/filebrowserview/lib/ListLayout/ListLayoutAdapter.java:116: error: cannot find symbol
                holder.fileFolderIcon.setImageResource(R.drawable.icon_mp3);
                                                                 ^
  symbol:   variable icon_mp3
  location: class drawable
FileBrowserView/library/src/main/java/com/psaravan/filebrowserview/lib/ListLayout/ListLayoutAdapter.java:120: error: cannot find symbol
                holder.fileFolderIcon.setImageResource(R.drawable.icon_png);
                                                                 ^
  symbol:   variable icon_png
  location: class drawable
FileBrowserView/library/src/main/java/com/psaravan/filebrowserview/lib/ListLayout/ListLayoutAdapter.java:124: error: cannot find symbol
                holder.fileFolderIcon.setImageResource(R.drawable.icon_avi);
                                                                 ^
  symbol:   variable icon_avi
  location: class drawable
FileBrowserView/library/src/main/java/com/psaravan/filebrowserview/lib/ListLayout/ListLayoutAdapter.java:128: error: cannot find symbol
                holder.fileFolderIcon.setImageResource(R.drawable.icon_default);
                                                                 ^
  symbol:   variable icon_default
  location: class drawable
5 errors
:library:compileReleaseJava FAILED
`

**Comment by psaravan** [comment]
Are you you're doing a manual Gradle build instead of compiling through Android Studio?

**Comment by 40ft** [comment]
yep. I use Eclipse.

**Comment by psaravan** [comment]
Looks like a linker problem with the library's resources. Have you added the library to your project's build path? I'm also going to put up a JAR file later today, which should avoid all these issues in the first place.

**Comment by 40ft** [comment]
which library? I'm just trying to build it in isolation from the command line.

Those icons referenced seem to be missing entirely from the project which would explain the compilation error. Did you forget to add them?

**Comment by psaravan** [comment]
Good catch, looks like my Android Studio wasn't pushing those icons into the git repo. Just updated the project with the icons. Go ahead and refork/redownload the entire project. It should work now.

**Comment by 40ft** [comment]
that did the trick. thanks.
